'use client';

// AUTO-GENERATED by scripts/generate-custom-icons.js from Figma set `amp-stories` (3646:10738).
// Do not edit — change the icon in Figma, then run: npm run icons:custom
// Not available in @mui/icons-material, so the DS ships it.

import { createSvgIcon } from '@mui/material/utils';

/** Figma `amp-stories` · Style=filled */
export const AmpStories = createSvgIcon([
  <path key="0" d="M17 4H7V19H17V4Z" />,
  <path key="1" d="M5 6H3V17H5V6Z" />,
  <path key="2" d="M21 6H19V17H21V6Z" />,
], 'AmpStories');

/** Figma `amp-stories` · Style=outlined */
export const AmpStoriesOutlined = createSvgIcon([
  <path key="0" d="M7 19H17V4H7V19ZM9 6H15V17H9V6Z" />,
  <path key="1" d="M5 6H3V17H5V6Z" />,
  <path key="2" d="M21 6H19V17H21V6Z" />,
], 'AmpStoriesOutlined');

/** Figma `amp-stories` · Style=rounded */
export const AmpStoriesRounded = createSvgIcon([
  <path key="0" d="M16 4H8C7.45 4 7 4.45 7 5V18C7 18.55 7.45 19 8 19H16C16.55 19 17 18.55 17 18V5C17 4.45 16.55 4 16 4Z" />,
  <path key="1" d="M4 6C3.45 6 3 6.45 3 7V16C3 16.55 3.45 17 4 17C4.55 17 5 16.55 5 16V7C5 6.45 4.55 6 4 6Z" />,
  <path key="2" d="M20 6C19.45 6 19 6.45 19 7V16C19 16.55 19.45 17 20 17C20.55 17 21 16.55 21 16V7C21 6.45 20.55 6 20 6Z" />,
], 'AmpStoriesRounded');

/** Figma `amp-stories` · Style=sharp */
export const AmpStoriesSharp = createSvgIcon([
  <path key="0" d="M17 4H7V19H17V4Z" />,
  <path key="1" d="M5 6H3V17H5V6Z" />,
  <path key="2" d="M21 6H19V17H21V6Z" />,
], 'AmpStoriesSharp');

/** Figma `amp-stories` · Style=two-tone */
export const AmpStoriesTwoTone = createSvgIcon([
  <path key="0" opacity="0.3" d="M15 6H9V17H15V6Z" />,
  <path key="1" d="M7 19H17V4H7V19ZM9 6H15V17H9V6Z" />,
  <path key="2" d="M5 6H3V17H5V6Z" />,
  <path key="3" d="M21 6H19V17H21V6Z" />,
], 'AmpStoriesTwoTone');
