'use client';

// AUTO-GENERATED by scripts/generate-custom-icons.js from Figma set `dock-to-right` (5440:5110).
// Do not edit — change the icon in Figma, then run: npm run icons:custom
// Not available in @mui/icons-material, so the DS ships it.

import { createSvgIcon } from '@mui/material/utils';

/** Figma `dock-to-right` · Style=filled */
export const DockToRight = createSvgIcon(<path d="M5 21C4.45 21 3.97917 20.8042 3.5875 20.4125C3.19583 20.0208 3 19.55 3 19V5C3 4.45 3.19583 3.97917 3.5875 3.5875C3.97917 3.19583 4.45 3 5 3H19C19.55 3 20.0208 3.19583 20.4125 3.5875C20.8042 3.97917 21 4.45 21 5V19C21 19.55 20.8042 20.0208 20.4125 20.4125C20.0208 20.8042 19.55 21 19 21H5ZM10 19H19V5H10V19Z" />, 'DockToRight');

/** Figma `dock-to-right` · Style=outlined */
export const DockToRightOutlined = createSvgIcon(<path d="M5 21C4.45 21 3.97917 20.8042 3.5875 20.4125C3.19583 20.0208 3 19.55 3 19V5C3 4.45 3.19583 3.97917 3.5875 3.5875C3.97917 3.19583 4.45 3 5 3H19C19.55 3 20.0208 3.19583 20.4125 3.5875C20.8042 3.97917 21 4.45 21 5V19C21 19.55 20.8042 20.0208 20.4125 20.4125C20.0208 20.8042 19.55 21 19 21H5ZM8 19V5H5V19H8ZM10 19H19V5H10V19Z" />, 'DockToRightOutlined');

/** Figma `dock-to-right` · Style=rounded */
export const DockToRightRounded = createSvgIcon(<path d="M5 21C4.45 21 3.97917 20.8042 3.5875 20.4125C3.19583 20.0208 3 19.55 3 19V5C3 4.45 3.19583 3.97917 3.5875 3.5875C3.97917 3.19583 4.45 3 5 3H19C19.55 3 20.0208 3.19583 20.4125 3.5875C20.8042 3.97917 21 4.45 21 5V19C21 19.55 20.8042 20.0208 20.4125 20.4125C20.0208 20.8042 19.55 21 19 21H5ZM8 19V5H5V19H8ZM10 19H19V5H10V19Z" />, 'DockToRightRounded');

/** Figma `dock-to-right` · Style=sharp */
export const DockToRightSharp = createSvgIcon(<path d="M5 19H8V5H5V19ZM10 19H19V5H10V19ZM3 21V3H21V21H3Z" />, 'DockToRightSharp');

/** Figma `dock-to-right` · Style=two-tone */
export const DockToRightTwoTone = createSvgIcon([
  <path key="0" opacity="0.3" d="M8 5V19H5V5H8ZM19 5V19H10V5H19Z" />,
  <path key="1" d="M5 21C4.45 21 3.97917 20.8042 3.5875 20.4125C3.19583 20.0208 3 19.55 3 19V5C3 4.45 3.19583 3.97917 3.5875 3.5875C3.97917 3.19583 4.45 3 5 3H19C19.55 3 20.0208 3.19583 20.4125 3.5875C20.8042 3.97917 21 4.45 21 5V19C21 19.55 20.8042 20.0208 20.4125 20.4125C20.0208 20.8042 19.55 21 19 21H5ZM8 19V5H5V19H8ZM10 19H19V5H10V19Z" />,
], 'DockToRightTwoTone');
