'use client';

// AUTO-GENERATED by scripts/generate-custom-icons.js from Figma set `exposure-plus-1` (3646:16151).
// Do not edit — change the icon in Figma, then run: npm run icons:custom
// Not available in @mui/icons-material, so the DS ships it.

import { createSvgIcon } from '@mui/material/utils';

/** Figma `exposure-plus-1` · Style=filled */
export const ExposurePlus1 = createSvgIcon(<path d="M10 7H8V11H4V13H8V17H10V13H14V11H10V7ZM20 18H18V7.38L15 8.4V6.7L19.7 5H20V18Z" />, 'ExposurePlus1');

/** Figma `exposure-plus-1` · Style=outlined */
export const ExposurePlus1Outlined = createSvgIcon(<path d="M10 7H8V11H4V13H8V17H10V13H14V11H10V7ZM20 18H18V7.38L15 8.4V6.7L19.7 5H20V18Z" />, 'ExposurePlus1Outlined');

/** Figma `exposure-plus-1` · Style=rounded */
export const ExposurePlus1Rounded = createSvgIcon(<path d="M9 7C8.45 7 8 7.45 8 8V11H5C4.45 11 4 11.45 4 12C4 12.55 4.45 13 5 13H8V16C8 16.55 8.45 17 9 17C9.55 17 10 16.55 10 16V13H13C13.55 13 14 12.55 14 12C14 11.45 13.55 11 13 11H10V8C10 7.45 9.55 7 9 7ZM20 18H18V7.38L15 8.4V6.7L19.7 5H20V18Z" />, 'ExposurePlus1Rounded');

/** Figma `exposure-plus-1` · Style=sharp */
export const ExposurePlus1Sharp = createSvgIcon(<path d="M10 7H8V11H4V13H8V17H10V13H14V11H10V7ZM20 18H18V7.38L15 8.4V6.7L19.7 5H20V18Z" />, 'ExposurePlus1Sharp');

/** Figma `exposure-plus-1` · Style=two-tone */
export const ExposurePlus1TwoTone = createSvgIcon(<path d="M20 18V5H19.7L15 6.7V8.4L18 7.38V18H20ZM10 17V13H14V11H10V7H8V11H4V13H8V17H10Z" />, 'ExposurePlus1TwoTone');
