#!/usr/bin/env bash
# Cloudflare Quick Tunnel — one URL for setup + peer API (proxy /v1/* on :3848).
# Requires: cloudflared, bridge on 3847/3848 (make peer-start).
set -euo pipefail

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$DIR"

if [[ -f .env ]]; then set -a; source .env; set +a; fi

SETUP_PORT="${PEER_SETUP_PORT:-3848}"
PEER_PORT="${PEER_PORT:-3847}"
CF_DIR="$DIR/.cloudflared"
LOG_DIR="$CF_DIR/quick-logs"
URL_FILE="$CF_DIR/quick-tunnel.urls"
PID_FILE="$CF_DIR/quick-setup.pid"
SETUP_LOG="$LOG_DIR/setup.log"

if ! command -v cloudflared >/dev/null 2>&1; then
  echo "Install: brew install cloudflared" >&2
  exit 1
fi

if ! curl -sf --max-time 2 "http://127.0.0.1:${SETUP_PORT}/api/detect" >/dev/null; then
  echo "Run make peer-start first (setup :${SETUP_PORT})" >&2
  exit 1
fi
if ! curl -sf --max-time 2 "http://127.0.0.1:${PEER_PORT}/health" >/dev/null; then
  echo "Run make peer-start first (peer :${PEER_PORT})" >&2
  exit 1
fi

stop_tunnel() {
  [[ -f "$PID_FILE" ]] || return 0
  local pid
  pid="$(cat "$PID_FILE")"
  if kill -0 "$pid" 2>/dev/null; then
    kill "$pid" 2>/dev/null || true
    sleep 1
  fi
  rm -f "$PID_FILE"
  # legacy second tunnel
  [[ -f "$CF_DIR/quick-peer.pid" ]] && kill "$(cat "$CF_DIR/quick-peer.pid")" 2>/dev/null || true
  rm -f "$CF_DIR/quick-peer.pid"
}

stop_tunnel
mkdir -p "$LOG_DIR"
: >"$SETUP_LOG"

wait_trycloudflare_url() {
  local log="$1"
  local deadline=$((SECONDS + 90))
  while (( SECONDS < deadline )); do
    if grep -q "Registered tunnel connection" "$log" 2>/dev/null; then
      local url
      url="$(grep -oE 'https://[a-zA-Z0-9.-]+\.trycloudflare\.com' "$log" 2>/dev/null | head -1 || true)"
      if [[ -n "$url" ]]; then
        echo "$url"
        return 0
      fi
    fi
    sleep 1
  done
  echo "Timeout waiting for tunnel — see $log" >&2
  return 1
}

verify_public() {
  local base="$1"
  local deadline=$((SECONDS + 90))
  while (( SECONDS < deadline )); do
    if curl -sf --max-time 10 "${base}/api/detect" >/dev/null 2>&1; then
      return 0
    fi
    sleep 3
  done
  return 1
}

launch_cloudflared() {
  nohup bash -c 'exec cloudflared tunnel --no-autoupdate --url "http://127.0.0.1:'"${SETUP_PORT}"'"' >>"$SETUP_LOG" 2>&1 &
  echo "$!" >"$PID_FILE"
  disown 2>/dev/null || true
}

echo "Starting Quick Tunnel (setup :${SETUP_PORT} → proxies /v1/* to :${PEER_PORT})…"
launch_cloudflared

SETUP_URL="$(wait_trycloudflare_url "$SETUP_LOG")"
echo "Got URL: ${SETUP_URL}"
echo "Verifying public access…"
TUNNEL_OK=0
if verify_public "$SETUP_URL"; then
  TUNNEL_OK=1
else
  pid="$(cat "$PID_FILE" 2>/dev/null || true)"
  if [[ -n "$pid" ]] && kill -0 "$pid" 2>/dev/null; then
    echo "⚠️  Tunnel ยังไม่ตอบจากภายนอก — cloudflared ยังรัน (pid $pid) ลอง curl อีกครั้งใน 1–2 นาที" >&2
  else
    echo "❌ cloudflared หยุดเอง — รันใน terminal แยก: make tunnel-quick-foreground" >&2
    exit 1
  fi
fi

cat >"$URL_FILE" <<EOF
# Auto-generated by make tunnel-quick — URLs change when tunnel restarts
PEER_PUBLIC_SETUP_URL=${SETUP_URL}
PEER_PUBLIC_PEER_URL=${SETUP_URL}
EOF

upsert_env() {
  local key="$1" val="$2" env_file="$DIR/.env"
  [[ -f "$env_file" ]] || cp "$DIR/.env.example" "$env_file"
  if grep -q "^${key}=" "$env_file" 2>/dev/null; then
    sed -i.bak "s|^${key}=.*|${key}=${val}|" "$env_file" && rm -f "$env_file.bak"
  else
    echo "${key}=${val}" >>"$env_file"
  fi
}

upsert_env PEER_PUBLIC_SETUP_URL "$SETUP_URL"
upsert_env PEER_PUBLIC_PEER_URL "$SETUP_URL"

echo "Restarting bridge so install.sh uses tunnel URL…"
PEER_FORCE_RESTART=1 bash "$DIR/scripts/start-background.sh" >/dev/null 2>&1 || true
sleep 2

echo ""
echo "══════════════════════════════════════"
echo "  Quick Tunnel พร้อม (URL เดียว)"
echo "══════════════════════════════════════"
echo "Public:  ${SETUP_URL}"
echo ""
echo "Guest curl:"
echo "  curl -fsSL ${SETUP_URL}/install.sh | bash -s -- ${SETUP_URL}"
echo ""
echo "Guest pair ขั้น 3 — Host URL:"
echo "  ${SETUP_URL}"
echo ""
echo "Host: make peer-url   (รหัส pairing ใหม่)"
echo "หยุด tunnel: make tunnel-quick-stop"
echo ""
echo "⚠️  URL เปลี่ยนทุกครั้งที่รัน tunnel-quick ใหม่"
echo "⚠️  ไม่มี Access — ใช้ชั่วคราว / trusted Guest เท่านั้น"
