'use client';

// AUTO-GENERATED by scripts/generate-custom-icons.js from Figma set `exposure-neg-1` (3646:16119).
// Do not edit — change the icon in Figma, then run: npm run icons:custom
// Not available in @mui/icons-material, so the DS ships it.

import { createSvgIcon } from '@mui/material/utils';

/** Figma `exposure-neg-1` · Style=filled */
export const ExposureNeg1 = createSvgIcon(<path d="M4 11V13H12V11H4ZM19 18H17V7.38L14 8.4V6.7L18.7 5H19V18Z" />, 'ExposureNeg1');

/** Figma `exposure-neg-1` · Style=outlined */
export const ExposureNeg1Outlined = createSvgIcon(<path d="M4 11V13H12V11H4ZM19 18H17V7.38L14 8.4V6.7L18.7 5H19V18Z" />, 'ExposureNeg1Outlined');

/** Figma `exposure-neg-1` · Style=rounded */
export const ExposureNeg1Rounded = createSvgIcon(<path d="M4 12C4 12.55 4.45 13 5 13H11C11.55 13 12 12.55 12 12C12 11.45 11.55 11 11 11H5C4.45 11 4 11.45 4 12ZM19 18H17V7.38L14 8.4V6.7L18.7 5H19V18Z" />, 'ExposureNeg1Rounded');

/** Figma `exposure-neg-1` · Style=sharp */
export const ExposureNeg1Sharp = createSvgIcon(<path d="M4 11V13H12V11H4ZM19 18H17V7.38L14 8.4V6.7L18.7 5H19V18Z" />, 'ExposureNeg1Sharp');

/** Figma `exposure-neg-1` · Style=two-tone */
export const ExposureNeg1TwoTone = createSvgIcon(<path d="M19 18V5H18.7L14 6.7V8.4L17 7.38V18H19ZM4 11H12V13H4V11Z" />, 'ExposureNeg1TwoTone');
