'use client';

// AUTO-GENERATED by scripts/generate-custom-icons.js from Figma set `polymer` (3646:5172).
// Do not edit — change the icon in Figma, then run: npm run icons:custom
// Not available in @mui/icons-material, so the DS ships it.

import { createSvgIcon } from '@mui/material/utils';

/** Figma `polymer` · Style=filled */
export const Polymer = createSvgIcon(<path d="M19 4H15L7.11 16.63L4.5 12L9 4H5L0.5 12L5 20H9L16.89 7.37L19.5 12L15 20H19L23.5 12L19 4Z" />, 'Polymer');

/** Figma `polymer` · Style=outlined */
export const PolymerOutlined = createSvgIcon(<path d="M19 4H15L7.11 16.63L4.5 12L9 4H5L0.5 12L5 20H9L16.89 7.37L19.5 12L15 20H19L23.5 12L19 4Z" />, 'PolymerOutlined');

/** Figma `polymer` · Style=rounded */
export const PolymerRounded = createSvgIcon(<path d="M19 4H15L7.11 16.63L4.5 12L9 4H5L0.5 12L5 20H9L16.89 7.37L19.5 12L15 20H19L23.5 12L19 4Z" />, 'PolymerRounded');

/** Figma `polymer` · Style=sharp */
export const PolymerSharp = createSvgIcon(<path d="M19 4H15L7.11 16.63L4.5 12L9 4H5L0.5 12L5 20H9L16.89 7.37L19.5 12L15 20H19L23.5 12L19 4Z" />, 'PolymerSharp');

/** Figma `polymer` · Style=two-tone */
export const PolymerTwoTone = createSvgIcon(<path d="M19 4H15L7.11 16.63L4.5 12L9 4H5L0.5 12L5 20H9L16.89 7.37L19.5 12L15 20H19L23.5 12L19 4Z" />, 'PolymerTwoTone');
