// AUTO-GENERATED by scripts/generate-icon-connect.js — do not edit.
// Regenerate: npm run icons:connect
import figma from '@figma/code-connect';
import { ActivityHeartbeat } from '../../code/core/icons/ActivityHeartbeat';
import { BabyBottle } from '../../code/core/icons/BabyBottle';
import { BabyCarriage } from '../../code/core/icons/BabyCarriage';
import { Bandage } from '../../code/core/icons/Bandage';
import { Bike } from '../../code/core/icons/Bike';
import { BodyScan } from '../../code/core/icons/BodyScan';
import { Bone } from '../../code/core/icons/Bone';
import { Brain } from '../../code/core/icons/Brain';
import { CheckupList } from '../../code/core/icons/CheckupList';
import { ClipboardHeart } from '../../code/core/icons/ClipboardHeart';
import { ClockHeart } from '../../code/core/icons/ClockHeart';
import { Coffin } from '../../code/core/icons/Coffin';
import { CustomEmergencyBed } from '../../code/core/icons/CustomEmergencyBed';
import { CustomHeartBeat } from '../../code/core/icons/CustomHeartBeat';
import { CustomHome } from '../../code/core/icons/CustomHome';
import { CustomNurese } from '../../code/core/icons/CustomNurese';
import { CustomReportMedical } from '../../code/core/icons/CustomReportMedical';
import { CustomStethoscope } from '../../code/core/icons/CustomStethoscope';
import { Dental } from '../../code/core/icons/Dental';
import { DeviceWatchHeart } from '../../code/core/icons/DeviceWatchHeart';
import { Disabled } from '../../code/core/icons/Disabled';
import { Disabled2 } from '../../code/core/icons/Disabled2';
import { Dna } from '../../code/core/icons/Dna';
import { Dna2 } from '../../code/core/icons/Dna2';
import { Ear } from '../../code/core/icons/Ear';
import { EarScan } from '../../code/core/icons/EarScan';
import { EmergencyBed } from '../../code/core/icons/EmergencyBed';
import { Empathize } from '../../code/core/icons/Empathize';
import { FaceMask } from '../../code/core/icons/FaceMask';
import { Fall } from '../../code/core/icons/Fall';
import { FingerprintScan } from '../../code/core/icons/FingerprintScan';
import { FirstAidKit } from '../../code/core/icons/FirstAidKit';
import { Flask } from '../../code/core/icons/Flask';
import { Flask2 } from '../../code/core/icons/Flask2';
import { GenderBigender } from '../../code/core/icons/GenderBigender';
import { GenderFemale } from '../../code/core/icons/GenderFemale';
import { GenderMale } from '../../code/core/icons/GenderMale';
import { GenderTransgender } from '../../code/core/icons/GenderTransgender';
import { Grave } from '../../code/core/icons/Grave';
import { HandSanitizer } from '../../code/core/icons/HandSanitizer';
import { HealthRecognition } from '../../code/core/icons/HealthRecognition';
import { HeartRateMonitor } from '../../code/core/icons/HeartRateMonitor';
import { Heartbeat } from '../../code/core/icons/Heartbeat';
import { Hospital } from '../../code/core/icons/Hospital';
import { HospitalCircle } from '../../code/core/icons/HospitalCircle';
import { LineScan } from '../../code/core/icons/LineScan';
import { Lungs } from '../../code/core/icons/Lungs';
import { Man } from '../../code/core/icons/Man';
import { Massage } from '../../code/core/icons/Massage';
import { MedicalCrossCircle } from '../../code/core/icons/MedicalCrossCircle';
import { MedicineSyrup } from '../../code/core/icons/MedicineSyrup';
import { Microscope } from '../../code/core/icons/Microscope';
import { MoodAnnoyed } from '../../code/core/icons/MoodAnnoyed';
import { MoodConfused } from '../../code/core/icons/MoodConfused';
import { MoodEmpty } from '../../code/core/icons/MoodEmpty';
import { MoodHappy } from '../../code/core/icons/MoodHappy';
import { MoodNervous } from '../../code/core/icons/MoodNervous';
import { MoodSad } from '../../code/core/icons/MoodSad';
import { MoodSmile } from '../../code/core/icons/MoodSmile';
import { MusicHeart } from '../../code/core/icons/MusicHeart';
import { Nurse } from '../../code/core/icons/Nurse';
import { Old } from '../../code/core/icons/Old';
import { Physiotherapist } from '../../code/core/icons/Physiotherapist';
import { PillCapsule } from '../../code/core/icons/PillCapsule';
import { Pills } from '../../code/core/icons/Pills';
import { PlayBasketball } from '../../code/core/icons/PlayBasketball';
import { Prescription } from '../../code/core/icons/Prescription';
import { Razor } from '../../code/core/icons/Razor';
import { RazorElectric } from '../../code/core/icons/RazorElectric';
import { ReportMedical } from '../../code/core/icons/ReportMedical';
import { ScaleOutline } from '../../code/core/icons/ScaleOutline';
import { ScubaDiving } from '../../code/core/icons/ScubaDiving';
import { Skateboarding } from '../../code/core/icons/Skateboarding';
import { Skull } from '../../code/core/icons/Skull';
import { Snowboarding } from '../../code/core/icons/Snowboarding';
import { Stethoscope } from '../../code/core/icons/Stethoscope';
import { Stretching } from '../../code/core/icons/Stretching';
import { Swimming } from '../../code/core/icons/Swimming';
import { TemperatureSnow } from '../../code/core/icons/TemperatureSnow';
import { TemperatureSun } from '../../code/core/icons/TemperatureSun';
import { Treadmill } from '../../code/core/icons/Treadmill';
import { UserHeart } from '../../code/core/icons/UserHeart';
import { Vaccine } from '../../code/core/icons/Vaccine';
import { VaccineBottle } from '../../code/core/icons/VaccineBottle';
import { Waterpolo } from '../../code/core/icons/Waterpolo';
import { Wheelchair } from '../../code/core/icons/Wheelchair';
import { Woman } from '../../code/core/icons/Woman';
import { WorldHeart } from '../../code/core/icons/WorldHeart';
import { Yoga } from '../../code/core/icons/Yoga';

// activity-heartbeat
figma.connect(ActivityHeartbeat, 'https://www.figma.com/design/XgxprkSY5mGbzIIwlmscCt/Cariva-Core-Design-System?node-id=5408-2865', {
  example: () => <ActivityHeartbeat />,
});

// baby-bottle
figma.connect(BabyBottle, 'https://www.figma.com/design/XgxprkSY5mGbzIIwlmscCt/Cariva-Core-Design-System?node-id=5408-2875', {
  example: () => <BabyBottle />,
});

// baby-carriage
figma.connect(BabyCarriage, 'https://www.figma.com/design/XgxprkSY5mGbzIIwlmscCt/Cariva-Core-Design-System?node-id=5408-2844', {
  example: () => <BabyCarriage />,
});

// bandage
figma.connect(Bandage, 'https://www.figma.com/design/XgxprkSY5mGbzIIwlmscCt/Cariva-Core-Design-System?node-id=5408-2843', {
  example: () => <Bandage />,
});

// bike
figma.connect(Bike, 'https://www.figma.com/design/XgxprkSY5mGbzIIwlmscCt/Cariva-Core-Design-System?node-id=5408-2897', {
  example: () => <Bike />,
});

// body-scan
figma.connect(BodyScan, 'https://www.figma.com/design/XgxprkSY5mGbzIIwlmscCt/Cariva-Core-Design-System?node-id=5408-2832', {
  example: () => <BodyScan />,
});

// bone
figma.connect(Bone, 'https://www.figma.com/design/XgxprkSY5mGbzIIwlmscCt/Cariva-Core-Design-System?node-id=5408-2888', {
  example: () => <Bone />,
});

// brain
figma.connect(Brain, 'https://www.figma.com/design/XgxprkSY5mGbzIIwlmscCt/Cariva-Core-Design-System?node-id=5408-2845', {
  example: () => <Brain />,
});

// checkup-list
figma.connect(CheckupList, 'https://www.figma.com/design/XgxprkSY5mGbzIIwlmscCt/Cariva-Core-Design-System?node-id=5408-2834', {
  example: () => <CheckupList />,
});

// clipboard-heart
figma.connect(ClipboardHeart, 'https://www.figma.com/design/XgxprkSY5mGbzIIwlmscCt/Cariva-Core-Design-System?node-id=5408-2829', {
  example: () => <ClipboardHeart />,
});

// clock-heart
figma.connect(ClockHeart, 'https://www.figma.com/design/XgxprkSY5mGbzIIwlmscCt/Cariva-Core-Design-System?node-id=5408-2864', {
  example: () => <ClockHeart />,
});

// coffin
figma.connect(Coffin, 'https://www.figma.com/design/XgxprkSY5mGbzIIwlmscCt/Cariva-Core-Design-System?node-id=5408-2885', {
  example: () => <Coffin />,
});

// custom-emergency-bed
figma.connect(CustomEmergencyBed, 'https://www.figma.com/design/XgxprkSY5mGbzIIwlmscCt/Cariva-Core-Design-System?node-id=5449-2825', {
  example: () => <CustomEmergencyBed />,
});

// custom-heart-beat
figma.connect(CustomHeartBeat, 'https://www.figma.com/design/XgxprkSY5mGbzIIwlmscCt/Cariva-Core-Design-System?node-id=5449-2828', {
  example: () => <CustomHeartBeat />,
});

// custom-home
figma.connect(CustomHome, 'https://www.figma.com/design/XgxprkSY5mGbzIIwlmscCt/Cariva-Core-Design-System?node-id=5449-2829', {
  example: () => <CustomHome />,
});

// custom-nurese
figma.connect(CustomNurese, 'https://www.figma.com/design/XgxprkSY5mGbzIIwlmscCt/Cariva-Core-Design-System?node-id=5507-4991', {
  example: () => <CustomNurese />,
});

// custom-report-medical
figma.connect(CustomReportMedical, 'https://www.figma.com/design/XgxprkSY5mGbzIIwlmscCt/Cariva-Core-Design-System?node-id=5449-2826', {
  example: () => <CustomReportMedical />,
});

// custom-stethoscope
figma.connect(CustomStethoscope, 'https://www.figma.com/design/XgxprkSY5mGbzIIwlmscCt/Cariva-Core-Design-System?node-id=5449-2827', {
  example: () => <CustomStethoscope />,
});

// dental
figma.connect(Dental, 'https://www.figma.com/design/XgxprkSY5mGbzIIwlmscCt/Cariva-Core-Design-System?node-id=5408-2846', {
  example: () => <Dental />,
});

// device-watch-heart
figma.connect(DeviceWatchHeart, 'https://www.figma.com/design/XgxprkSY5mGbzIIwlmscCt/Cariva-Core-Design-System?node-id=5408-2835', {
  example: () => <DeviceWatchHeart />,
});

// disabled
figma.connect(Disabled, 'https://www.figma.com/design/XgxprkSY5mGbzIIwlmscCt/Cariva-Core-Design-System?node-id=5408-2841', {
  example: () => <Disabled />,
});

// disabled-2
figma.connect(Disabled2, 'https://www.figma.com/design/XgxprkSY5mGbzIIwlmscCt/Cariva-Core-Design-System?node-id=5408-2840', {
  example: () => <Disabled2 />,
});

// dna
figma.connect(Dna, 'https://www.figma.com/design/XgxprkSY5mGbzIIwlmscCt/Cariva-Core-Design-System?node-id=5408-2881', {
  example: () => <Dna />,
});

// dna-2
figma.connect(Dna2, 'https://www.figma.com/design/XgxprkSY5mGbzIIwlmscCt/Cariva-Core-Design-System?node-id=5408-2874', {
  example: () => <Dna2 />,
});

// ear
figma.connect(Ear, 'https://www.figma.com/design/XgxprkSY5mGbzIIwlmscCt/Cariva-Core-Design-System?node-id=5408-2847', {
  example: () => <Ear />,
});

// ear-scan
figma.connect(EarScan, 'https://www.figma.com/design/XgxprkSY5mGbzIIwlmscCt/Cariva-Core-Design-System?node-id=5408-2839', {
  example: () => <EarScan />,
});

// emergency-bed
figma.connect(EmergencyBed, 'https://www.figma.com/design/XgxprkSY5mGbzIIwlmscCt/Cariva-Core-Design-System?node-id=5408-2852', {
  example: () => <EmergencyBed />,
});

// empathize
figma.connect(Empathize, 'https://www.figma.com/design/XgxprkSY5mGbzIIwlmscCt/Cariva-Core-Design-System?node-id=5408-2849', {
  example: () => <Empathize />,
});

// face-mask
figma.connect(FaceMask, 'https://www.figma.com/design/XgxprkSY5mGbzIIwlmscCt/Cariva-Core-Design-System?node-id=5408-2851', {
  example: () => <FaceMask />,
});

// fall
figma.connect(Fall, 'https://www.figma.com/design/XgxprkSY5mGbzIIwlmscCt/Cariva-Core-Design-System?node-id=5408-2848', {
  example: () => <Fall />,
});

// fingerprint-scan
figma.connect(FingerprintScan, 'https://www.figma.com/design/XgxprkSY5mGbzIIwlmscCt/Cariva-Core-Design-System?node-id=5408-2871', {
  example: () => <FingerprintScan />,
});

// first-aid-kit
figma.connect(FirstAidKit, 'https://www.figma.com/design/XgxprkSY5mGbzIIwlmscCt/Cariva-Core-Design-System?node-id=5408-2830', {
  example: () => <FirstAidKit />,
});

// flask
figma.connect(Flask, 'https://www.figma.com/design/XgxprkSY5mGbzIIwlmscCt/Cariva-Core-Design-System?node-id=5408-2878', {
  example: () => <Flask />,
});

// flask-2
figma.connect(Flask2, 'https://www.figma.com/design/XgxprkSY5mGbzIIwlmscCt/Cariva-Core-Design-System?node-id=5408-2877', {
  example: () => <Flask2 />,
});

// gender-bigender
figma.connect(GenderBigender, 'https://www.figma.com/design/XgxprkSY5mGbzIIwlmscCt/Cariva-Core-Design-System?node-id=5408-2889', {
  example: () => <GenderBigender />,
});

// gender-female
figma.connect(GenderFemale, 'https://www.figma.com/design/XgxprkSY5mGbzIIwlmscCt/Cariva-Core-Design-System?node-id=5408-2891', {
  example: () => <GenderFemale />,
});

// gender-male
figma.connect(GenderMale, 'https://www.figma.com/design/XgxprkSY5mGbzIIwlmscCt/Cariva-Core-Design-System?node-id=5408-2887', {
  example: () => <GenderMale />,
});

// gender-transgender
figma.connect(GenderTransgender, 'https://www.figma.com/design/XgxprkSY5mGbzIIwlmscCt/Cariva-Core-Design-System?node-id=5408-2890', {
  example: () => <GenderTransgender />,
});

// grave
figma.connect(Grave, 'https://www.figma.com/design/XgxprkSY5mGbzIIwlmscCt/Cariva-Core-Design-System?node-id=5408-2884', {
  example: () => <Grave />,
});

// hand-sanitizer
figma.connect(HandSanitizer, 'https://www.figma.com/design/XgxprkSY5mGbzIIwlmscCt/Cariva-Core-Design-System?node-id=5408-2853', {
  example: () => <HandSanitizer />,
});

// health-recognition
figma.connect(HealthRecognition, 'https://www.figma.com/design/XgxprkSY5mGbzIIwlmscCt/Cariva-Core-Design-System?node-id=5408-2825', {
  example: () => <HealthRecognition />,
});

// heart-rate-monitor
figma.connect(HeartRateMonitor, 'https://www.figma.com/design/XgxprkSY5mGbzIIwlmscCt/Cariva-Core-Design-System?node-id=5408-2828', {
  example: () => <HeartRateMonitor />,
});

// heartbeat
figma.connect(Heartbeat, 'https://www.figma.com/design/XgxprkSY5mGbzIIwlmscCt/Cariva-Core-Design-System?node-id=5408-2882', {
  example: () => <Heartbeat />,
});

// hospital
figma.connect(Hospital, 'https://www.figma.com/design/XgxprkSY5mGbzIIwlmscCt/Cariva-Core-Design-System?node-id=5408-2827', {
  example: () => <Hospital />,
});

// hospital-circle
figma.connect(HospitalCircle, 'https://www.figma.com/design/XgxprkSY5mGbzIIwlmscCt/Cariva-Core-Design-System?node-id=5408-2826', {
  example: () => <HospitalCircle />,
});

// line-scan
figma.connect(LineScan, 'https://www.figma.com/design/XgxprkSY5mGbzIIwlmscCt/Cariva-Core-Design-System?node-id=5408-2872', {
  example: () => <LineScan />,
});

// lungs
figma.connect(Lungs, 'https://www.figma.com/design/XgxprkSY5mGbzIIwlmscCt/Cariva-Core-Design-System?node-id=5408-2842', {
  example: () => <Lungs />,
});

// man
figma.connect(Man, 'https://www.figma.com/design/XgxprkSY5mGbzIIwlmscCt/Cariva-Core-Design-System?node-id=5408-2893', {
  example: () => <Man />,
});

// massage
figma.connect(Massage, 'https://www.figma.com/design/XgxprkSY5mGbzIIwlmscCt/Cariva-Core-Design-System?node-id=5408-2880', {
  example: () => <Massage />,
});

// medical-cross-circle
figma.connect(MedicalCrossCircle, 'https://www.figma.com/design/XgxprkSY5mGbzIIwlmscCt/Cariva-Core-Design-System?node-id=5408-2833', {
  example: () => <MedicalCrossCircle />,
});

// medicine-syrup
figma.connect(MedicineSyrup, 'https://www.figma.com/design/XgxprkSY5mGbzIIwlmscCt/Cariva-Core-Design-System?node-id=5408-2831', {
  example: () => <MedicineSyrup />,
});

// microscope
figma.connect(Microscope, 'https://www.figma.com/design/XgxprkSY5mGbzIIwlmscCt/Cariva-Core-Design-System?node-id=5408-2879', {
  example: () => <Microscope />,
});

// mood-annoyed
figma.connect(MoodAnnoyed, 'https://www.figma.com/design/XgxprkSY5mGbzIIwlmscCt/Cariva-Core-Design-System?node-id=5408-2906', {
  example: () => <MoodAnnoyed />,
});

// mood-confused
figma.connect(MoodConfused, 'https://www.figma.com/design/XgxprkSY5mGbzIIwlmscCt/Cariva-Core-Design-System?node-id=5408-2907', {
  example: () => <MoodConfused />,
});

// mood-empty
figma.connect(MoodEmpty, 'https://www.figma.com/design/XgxprkSY5mGbzIIwlmscCt/Cariva-Core-Design-System?node-id=5408-2903', {
  example: () => <MoodEmpty />,
});

// mood-happy
figma.connect(MoodHappy, 'https://www.figma.com/design/XgxprkSY5mGbzIIwlmscCt/Cariva-Core-Design-System?node-id=5408-2905', {
  example: () => <MoodHappy />,
});

// mood-nervous
figma.connect(MoodNervous, 'https://www.figma.com/design/XgxprkSY5mGbzIIwlmscCt/Cariva-Core-Design-System?node-id=5408-2901', {
  example: () => <MoodNervous />,
});

// mood-sad
figma.connect(MoodSad, 'https://www.figma.com/design/XgxprkSY5mGbzIIwlmscCt/Cariva-Core-Design-System?node-id=5408-2904', {
  example: () => <MoodSad />,
});

// mood-smile
figma.connect(MoodSmile, 'https://www.figma.com/design/XgxprkSY5mGbzIIwlmscCt/Cariva-Core-Design-System?node-id=5408-2902', {
  example: () => <MoodSmile />,
});

// music-heart
figma.connect(MusicHeart, 'https://www.figma.com/design/XgxprkSY5mGbzIIwlmscCt/Cariva-Core-Design-System?node-id=5408-2867', {
  example: () => <MusicHeart />,
});

// nurse
figma.connect(Nurse, 'https://www.figma.com/design/XgxprkSY5mGbzIIwlmscCt/Cariva-Core-Design-System?node-id=5408-2854', {
  example: () => <Nurse />,
});

// old
figma.connect(Old, 'https://www.figma.com/design/XgxprkSY5mGbzIIwlmscCt/Cariva-Core-Design-System?node-id=5408-2850', {
  example: () => <Old />,
});

// physiotherapist
figma.connect(Physiotherapist, 'https://www.figma.com/design/XgxprkSY5mGbzIIwlmscCt/Cariva-Core-Design-System?node-id=5408-2870', {
  example: () => <Physiotherapist />,
});

// pill-capsule
figma.connect(PillCapsule, 'https://www.figma.com/design/XgxprkSY5mGbzIIwlmscCt/Cariva-Core-Design-System?node-id=5408-2855', {
  example: () => <PillCapsule />,
});

// pills
figma.connect(Pills, 'https://www.figma.com/design/XgxprkSY5mGbzIIwlmscCt/Cariva-Core-Design-System?node-id=5408-2856', {
  example: () => <Pills />,
});

// play-basketball
figma.connect(PlayBasketball, 'https://www.figma.com/design/XgxprkSY5mGbzIIwlmscCt/Cariva-Core-Design-System?node-id=5408-2898', {
  example: () => <PlayBasketball />,
});

// prescription
figma.connect(Prescription, 'https://www.figma.com/design/XgxprkSY5mGbzIIwlmscCt/Cariva-Core-Design-System?node-id=5408-2857', {
  example: () => <Prescription />,
});

// razor
figma.connect(Razor, 'https://www.figma.com/design/XgxprkSY5mGbzIIwlmscCt/Cariva-Core-Design-System?node-id=5408-2859', {
  example: () => <Razor />,
});

// razor-electric
figma.connect(RazorElectric, 'https://www.figma.com/design/XgxprkSY5mGbzIIwlmscCt/Cariva-Core-Design-System?node-id=5408-2858', {
  example: () => <RazorElectric />,
});

// report-medical
figma.connect(ReportMedical, 'https://www.figma.com/design/XgxprkSY5mGbzIIwlmscCt/Cariva-Core-Design-System?node-id=5408-2836', {
  example: () => <ReportMedical />,
});

// scale-outline
figma.connect(ScaleOutline, 'https://www.figma.com/design/XgxprkSY5mGbzIIwlmscCt/Cariva-Core-Design-System?node-id=5408-2860', {
  example: () => <ScaleOutline />,
});

// scuba-diving
figma.connect(ScubaDiving, 'https://www.figma.com/design/XgxprkSY5mGbzIIwlmscCt/Cariva-Core-Design-System?node-id=5408-2894', {
  example: () => <ScubaDiving />,
});

// skateboarding
figma.connect(Skateboarding, 'https://www.figma.com/design/XgxprkSY5mGbzIIwlmscCt/Cariva-Core-Design-System?node-id=5408-2895', {
  example: () => <Skateboarding />,
});

// skull
figma.connect(Skull, 'https://www.figma.com/design/XgxprkSY5mGbzIIwlmscCt/Cariva-Core-Design-System?node-id=5408-2883', {
  example: () => <Skull />,
});

// snowboarding
figma.connect(Snowboarding, 'https://www.figma.com/design/XgxprkSY5mGbzIIwlmscCt/Cariva-Core-Design-System?node-id=5408-2900', {
  example: () => <Snowboarding />,
});

// stethoscope
figma.connect(Stethoscope, 'https://www.figma.com/design/XgxprkSY5mGbzIIwlmscCt/Cariva-Core-Design-System?node-id=5408-2837', {
  example: () => <Stethoscope />,
});

// stretching
figma.connect(Stretching, 'https://www.figma.com/design/XgxprkSY5mGbzIIwlmscCt/Cariva-Core-Design-System?node-id=5408-2886', {
  example: () => <Stretching />,
});

// swimming
figma.connect(Swimming, 'https://www.figma.com/design/XgxprkSY5mGbzIIwlmscCt/Cariva-Core-Design-System?node-id=5408-2899', {
  example: () => <Swimming />,
});

// temperature-snow
figma.connect(TemperatureSnow, 'https://www.figma.com/design/XgxprkSY5mGbzIIwlmscCt/Cariva-Core-Design-System?node-id=5408-2869', {
  example: () => <TemperatureSnow />,
});

// temperature-sun
figma.connect(TemperatureSun, 'https://www.figma.com/design/XgxprkSY5mGbzIIwlmscCt/Cariva-Core-Design-System?node-id=5408-2866', {
  example: () => <TemperatureSun />,
});

// treadmill
figma.connect(Treadmill, 'https://www.figma.com/design/XgxprkSY5mGbzIIwlmscCt/Cariva-Core-Design-System?node-id=5408-2838', {
  example: () => <Treadmill />,
});

// user-heart
figma.connect(UserHeart, 'https://www.figma.com/design/XgxprkSY5mGbzIIwlmscCt/Cariva-Core-Design-System?node-id=5408-2863', {
  example: () => <UserHeart />,
});

// vaccine
figma.connect(Vaccine, 'https://www.figma.com/design/XgxprkSY5mGbzIIwlmscCt/Cariva-Core-Design-System?node-id=5408-2876', {
  example: () => <Vaccine />,
});

// vaccine-bottle
figma.connect(VaccineBottle, 'https://www.figma.com/design/XgxprkSY5mGbzIIwlmscCt/Cariva-Core-Design-System?node-id=5408-2861', {
  example: () => <VaccineBottle />,
});

// waterpolo
figma.connect(Waterpolo, 'https://www.figma.com/design/XgxprkSY5mGbzIIwlmscCt/Cariva-Core-Design-System?node-id=5408-2896', {
  example: () => <Waterpolo />,
});

// wheelchair
figma.connect(Wheelchair, 'https://www.figma.com/design/XgxprkSY5mGbzIIwlmscCt/Cariva-Core-Design-System?node-id=5408-2862', {
  example: () => <Wheelchair />,
});

// woman
figma.connect(Woman, 'https://www.figma.com/design/XgxprkSY5mGbzIIwlmscCt/Cariva-Core-Design-System?node-id=5408-2892', {
  example: () => <Woman />,
});

// world-heart
figma.connect(WorldHeart, 'https://www.figma.com/design/XgxprkSY5mGbzIIwlmscCt/Cariva-Core-Design-System?node-id=5408-2868', {
  example: () => <WorldHeart />,
});

// yoga
figma.connect(Yoga, 'https://www.figma.com/design/XgxprkSY5mGbzIIwlmscCt/Cariva-Core-Design-System?node-id=5408-2873', {
  example: () => <Yoga />,
});
